ribbon:
  IsSecure: false

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

---

spring:
  profiles: pact

ribbon:
  eureka:
    enabled: false

hystrix:
  command:
    randomFortune:
      execution.isolation.thread.timeoutInMilliseconds: 2000

fortunes:
  ribbon:
    listOfServers: localhost:8080
    
zuul:
  ignoredServices: "*"
  routes:
    fortunes: /**
